# Generated by Django 5.1.3 on 2024-12-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AroAddress",
            fields=[
                ("address_id", models.IntegerField(primary_key=True, serialize=False)),
                ("address_type", models.CharField(max_length=10)),
                ("address_line1", models.CharField(max_length=60)),
                (
                    "address_line2",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                ("city", models.CharField(max_length=30)),
                ("state", models.CharField(max_length=30)),
                ("zip_code", models.CharField(max_length=10)),
                ("country", models.CharField(max_length=30)),
                ("aro_address_address_id", models.IntegerField()),
            ],
            options={
                "db_table": "aro_address",
                "db_table_comment": "Address Table",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AroBooking",
            fields=[
                ("booking_id", models.IntegerField(primary_key=True, serialize=False)),
                ("passenger_id", models.IntegerField()),
                ("group_id", models.IntegerField()),
                ("booking_cost", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "db_table": "aro_booking",
                "db_table_comment": "PRIMARY KEY OF THE BOOKING TABLE",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AroEntertainments",
            fields=[
                (
                    "entertainment_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("entertainment_name", models.CharField(max_length=30)),
                ("number_units", models.IntegerField()),
                ("age_limit", models.IntegerField()),
                ("floor", models.IntegerField()),
            ],
            options={
                "db_table": "aro_entertainments",
                "db_table_comment": "PRIMARY KEY OF THE ENTERTAINMENT TABLE",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AroInvoice",
            fields=[
                ("invoice_id", models.IntegerField(primary_key=True, serialize=False)),
                ("issue_date", models.DateField()),
                ("due_date", models.DateField()),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "db_table": "aro_invoice",
                "db_table_comment": "PRIMARY KEY OF THE INVOICE TABLE",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AroPackages",
            fields=[
                ("package_id", models.IntegerField(primary_key=True, serialize=False)),
                ("package_name", models.CharField(max_length=30)),
                ("package_price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("price_type", models.CharField(max_length=5)),
            ],
            options={
                "db_table": "aro_packages",
                "db_table_comment": "PRIMARY KEY OF THE PACKAGE TABLE",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AroPassenger",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("passenger_id", models.IntegerField()),
                ("group_id", models.IntegerField()),
                ("fname", models.CharField(max_length=30)),
                ("lname", models.CharField(max_length=30)),
                ("gender", models.CharField(max_length=10)),
                ("age", models.IntegerField()),
                ("email", models.CharField(max_length=30)),
                ("phone", models.CharField(max_length=20)),
                ("nationality", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "aro_passenger",
                "db_table_comment": "PRIMARY KEY OF THE PASSENGER TABLE",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AroPayments",
            fields=[
                ("payment_id", models.IntegerField(primary_key=True, serialize=False)),
                ("trip_id", models.IntegerField()),
                ("payment_date", models.DateField()),
                ("payment_method", models.CharField(max_length=30)),
                (
                    "payment_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("group_id", models.IntegerField()),
                ("payment_status", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "aro_payments",
                "db_table_comment": "PRIMARY KEY OF THE PAYMENTS TABLE",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AroPort",
            fields=[
                ("port_id", models.IntegerField(primary_key=True, serialize=False)),
                ("port_name", models.CharField(max_length=30)),
                ("airport", models.CharField(max_length=30)),
                ("parking_spots", models.IntegerField()),
            ],
            options={
                "db_table": "aro_port",
                "db_table_comment": "PRIMARY KEY OF THE PORT",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AroRestaurants",
            fields=[
                (
                    "restaurant_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("restaurant_name", models.CharField(max_length=30)),
                ("opening_time", models.TimeField()),
                ("closing_time", models.TimeField()),
                ("floor", models.IntegerField()),
                (
                    "breakfast",
                    models.CharField(choices=[("Y", "Yes"), ("N", "No")], max_length=1),
                ),
                (
                    "lunch",
                    models.CharField(choices=[("Y", "Yes"), ("N", "No")], max_length=1),
                ),
                (
                    "dinner",
                    models.CharField(choices=[("Y", "Yes"), ("N", "No")], max_length=1),
                ),
            ],
            options={
                "db_table": "aro_restaurants",
                "db_table_comment": "PRIMARY KEY OF THE RESTAURANT TABLE",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AroRooms",
            fields=[
                ("room_number", models.IntegerField(primary_key=True, serialize=False)),
                ("room_type", models.CharField(max_length=20)),
                ("room_size", models.IntegerField()),
                ("number_beds", models.IntegerField()),
                ("number_bath", models.DecimalField(decimal_places=1, max_digits=2)),
                ("number_balcony", models.IntegerField()),
                ("room_location", models.CharField(max_length=10)),
                ("room_price", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                "db_table": "aro_rooms",
                "db_table_comment": "PRIMARY KEY OF THE ROOM TABLE",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AroTrip",
            fields=[
                ("trip_id", models.IntegerField(primary_key=True, serialize=False)),
                ("number_passengers", models.IntegerField()),
                ("ship_name", models.CharField(max_length=30)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("start_port", models.CharField(max_length=20)),
                ("end_port", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "aro_trip",
                "db_table_comment": "PRIMARY KEY OF THE TRIP TABLE",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EntertainmentTrip",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "entertainment_trip",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PassengerPackage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("group_id", models.IntegerField()),
                ("passenger_id", models.IntegerField()),
            ],
            options={
                "db_table": "passenger_package",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PassengerTrip",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("passenger_id", models.IntegerField()),
                ("group_id", models.IntegerField()),
            ],
            options={
                "db_table": "passenger_trip",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RestaurantsTrip",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "restaurants_trip",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RoomTrip",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "room_trip",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TripPort",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("arrival_date", models.DateField()),
                ("departure_date", models.DateField()),
            ],
            options={
                "db_table": "trip_port",
                "db_table_comment": "Trip Port Table",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
    ]
