# Generated by Django 5.1.3 on 2024-12-06 23:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aropassenger",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="passengertrip",
            options={"managed": True},
        ),
    ]
