# Generated by Django 5.1.3 on 2024-12-09 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_aropassenger_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="passengertrip",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="aropassenger",
            unique_together={("passenger_id", "group_id")},
        ),
        migrations.AddField(
            model_name="aropassenger",
            name="address",
            field=models.ForeignKey(
                blank=True,
                db_column="address_id",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.aroaddress",
            ),
        ),
        migrations.AddField(
            model_name="aropassenger",
            name="room_number",
            field=models.ForeignKey(
                blank=True,
                db_column="room_number",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.arorooms",
            ),
        ),
        migrations.AddField(
            model_name="aropassenger",
            name="user_id",
            field=models.ForeignKey(
                blank=True,
                db_column="user_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="passengertrip",
            name="trip_id",
            field=models.ForeignKey(
                blank=True,
                db_column="trip_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.arotrip",
            ),
        ),
        migrations.AlterField(
            model_name="aropassenger",
            name="passenger_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="passengertrip",
            name="group_id",
            field=models.ForeignKey(
                db_column="group_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trip_groups",
                to="api.aropassenger",
            ),
        ),
        migrations.AlterField(
            model_name="passengertrip",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="passengertrip",
            name="passenger_id",
            field=models.ForeignKey(
                db_column="passenger_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trip_passengers",
                to="api.aropassenger",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="passengertrip",
            unique_together={("trip_id", "passenger_id", "group_id")},
        ),
        migrations.AlterModelTable(
            name="passengertrip",
            table=None,
        ),
        migrations.RemoveField(
            model_name="aropassenger",
            name="id",
        ),
    ]
